---
- name: Playbook para hacer el deploy de Wordpress
  hosts: frontend
  become: yes

  vars_files:
    - vars/variables.yml

  tasks:

    - name: Crear una base de datos
      mysql_db:
        name: "{{ db.name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 

    - name: Crear el usuario de la base de datos
      mysql_user:         
        name: "{{ db.user }}"
        password: "{{ db.password }}"
        priv: "{{ db.name }}.*:ALL"
        #host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 


    - name: Descargar el código fuente de GitHub

      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
        force: yes

    - name: Descomprimir archivo

      unarchive:
        src: /tmp/wordpress.zip
        dest: /tmp
        remote_src: yes


    - name: Muevo el código fuente a la carpeta raíz

      copy:
        src: /tmp/wordpress/
        dest: /var/www/html/wordpress
        remote_src: yes
        mode: 0755

    - name: Creamos el archivo de configuracion de wordpress

      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        remote_src: yes
        mode: 0755

    - name: Editar el nombre de la base de datos en el archivo de configuración

      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "database_name_here"
        replace: "{{ db.name }}"

    - name: Editar el usuario de la base de datos en el archivo de configuración

      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "username_here"
        replace: "{{ db.user }}"

    - name: Editar el password del usuario de la base de datos en el archivo de configuración

      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "password_here"
        replace: "{{ db.password }}"



    - name: Cambiar el propietario del directorio /var/www/html

      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes