version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysql --user=${WORDPRESS_DB_USER} --password=${WORDPRESS_DB_PASSWORD} -e "SHOW DATABASES;"
      interval: 1s
      timeout: 3s
      retries: 3
    networks:
      - backend-network
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    restart: always

volumes: 
  mysql_data:
  wordpress_data:

networks:
  frontend-network:
  backend-network: