---
- name: Playbook para instalar WordPress 
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks: 

    - name: Descargar el codigo fuente de WordPress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/latest.zip

    - name: Instalar unzip
      apt:
        name: unzip
        state: present

    - name: Descomprimir WordPress
      unarchive:
        src: /tmp/latest.zip
        dest: /tmp/
        remote_src: yes

    - name: Copiar WordPress
      copy:
        src: /tmp/wordpress/
        dest: /var/www/html/wordpress
        remote_src: yes
    
    - name: A単adir a la configuracion el nombre de la base de datos
      ansible.builtin.replace:
        path: /var/www/html/wordpress/wp-config-sample.php
        regexp: 'database_name_here'
        replace: '{{ db.name }}'

    - name: A単adir a la configuracion el nombre de usuario
      ansible.builtin.replace:
        path: /var/www/html/wordpress/wp-config-sample.php
        regexp: 'username_here'
        replace: '{{ db.user }}'

    - name: A単adir a la configuracion la contrase単a
      ansible.builtin.replace:
        path: /var/www/html/wordpress/wp-config-sample.php
        regexp: 'password_here'
        replace: '{{ db.password }}'

    - name: Borrar el archivo index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Cambiar el propietario y el grupo de WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        recurse: yes